version: "3"

services:
  business_logic:
    build: ./business_logic
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  db:
    image: mysql:8.1
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql

  # process_centric:
  #   build: ./process_centric
  #   depends_on:
  #     - business_logic
