version: "3"

services:
  ocr_service:
    build: ./ocr_service
    ports:
      - "5003:5003"

  chatgpt_service:
    build: ./chatgpt_service
    links:
      - scheduler_service
    ports:
      - "5002:5002"
    env_file:
    - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - scheduler_service

  scheduler_service:
    build: ./scheduler_service
    links:
      - flashcard_service
    ports:
      - "5001:5001"
    environment:
      - DL_URL=http://flashcard_service:5000
      - CHATGPT_URL=http://chatgpt_service:5002
    depends_on:
      - flashcard_service

  flashcard_service:
    build: ./flashcard_service
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  db:
    image: mysql:8.1
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./flashcard_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql

  # telegram_bot:
  #   build: ./telegram_bot
  #   depends_on:
  #     - scheduler_service
  #     - chatgpt_service
  #     - ocr_service
  #     - flashcard_service
  #   environment:
  #     - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
  #     - CHATGPT_URL=http://chatgpt_service:5002
  #     - OCR_URL=http://ocr_service:5003
  #     - SCHEDULER_URL=http://scheduler_service:5001
  #     - DL_URL=http://flashcard_service:5000
  #   links:
  #     - scheduler_service
  #     - chatgpt_service
  #     - ocr_service
  #     - flashcard_service
  #   env_file:
  #   - .env

